/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./App.tsx", "./src/**/*.{ts,tsx}"],
  presets: [require("nativewind/preset")],
  theme: {
    extend: {
      colors: {
        background: "#131319",
        surface: "#131319",
        "surface-dim": "#131319",
        "surface-bright": "#393840",
        "surface-container-lowest": "#0e0e14",
        "surface-container-low": "#1b1b21",
        "surface-container": "#1f1f25",
        "surface-container-high": "#2a2930",
        "surface-container-highest": "#35343b",
        "surface-variant": "#35343b",
        "on-background": "#e4e1ea",
        "on-surface": "#e4e1ea",
        "on-surface-variant": "#dfbec9",
        "inverse-surface": "#e4e1ea",
        "inverse-on-surface": "#303037",
        outline: "#a78993",
        "outline-variant": "#584049",
        "surface-tint": "#ffb0ce",
        primary: "#ffb0ce",
        "on-primary": "#63003b",
        "primary-container": "#fc49a5",
        "on-primary-container": "#570033",
        "inverse-primary": "#b70070",
        "primary-fixed": "#ffd9e5",
        "primary-fixed-dim": "#ffb0ce",
        "on-primary-fixed": "#3e0022",
        "on-primary-fixed-variant": "#8c0055",
        secondary: "#d1bcff",
        "on-secondary": "#3c0090",
        "secondary-container": "#5910c8",
        "on-secondary-container": "#c4abff",
        "secondary-fixed": "#e9ddff",
        "secondary-fixed-dim": "#d1bcff",
        "on-secondary-fixed": "#23005b",
        "on-secondary-fixed-variant": "#5608c6",
        tertiary: "#00dbe9",
        "on-tertiary": "#00363a",
        "tertiary-container": "#00a0aa",
        "on-tertiary-container": "#002f33",
        "tertiary-fixed": "#7df4ff",
        "tertiary-fixed-dim": "#00dbe9",
        "on-tertiary-fixed": "#002022",
        "on-tertiary-fixed-variant": "#004f54",
        error: "#ffb4ab",
        "on-error": "#690005",
        "error-container": "#93000a",
        "on-error-container": "#ffdad6",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
        full: "9999px",
      },
      spacing: {
        "space-2xs": "0.25rem",
        "space-xs": "0.5rem",
        "space-sm": "0.75rem",
        "space-md": "1rem",
        "space-lg": "1.25rem",
        "space-xl": "1.5rem",
        "space-2xl": "2rem",
        "space-3xl": "3rem",
        "margin-mobile": "1.25rem",
        "gutter-mobile": "0.75rem",
      },
      fontFamily: {
        "headline-2xl-mobile": ["PlusJakartaSans_800ExtraBold"],
        "headline-2xl": ["PlusJakartaSans_800ExtraBold"],
        "headline-xl": ["PlusJakartaSans_700Bold"],
        "headline-lg": ["PlusJakartaSans_700Bold"],
        "headline-md": ["PlusJakartaSans_600SemiBold"],
        "body-lg": ["PlusJakartaSans_400Regular"],
        "body-md": ["PlusJakartaSans_400Regular"],
        "body-sm": ["PlusJakartaSans_400Regular"],
        "label-lg": ["SpaceGrotesk_600SemiBold"],
        "label-md": ["SpaceGrotesk_600SemiBold"],
        "label-sm": ["SpaceGrotesk_700Bold"],
      },
      fontSize: {
        "headline-2xl-mobile": ["32px", { lineHeight: "38px", letterSpacing: "-0.025em" }],
        "headline-2xl": ["40px", { lineHeight: "48px", letterSpacing: "-0.03em" }],
        "headline-xl": ["28px", { lineHeight: "34px", letterSpacing: "-0.02em" }],
        "headline-lg": ["22px", { lineHeight: "28px", letterSpacing: "-0.015em" }],
        "headline-md": ["18px", { lineHeight: "24px", letterSpacing: "-0.01em" }],
        "body-lg": ["16px", { lineHeight: "24px" }],
        "body-md": ["14px", { lineHeight: "20px" }],
        "body-sm": ["12px", { lineHeight: "16px" }],
        "label-lg": ["14px", { lineHeight: "18px", letterSpacing: "0.02em" }],
        "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.04em" }],
        "label-sm": ["10px", { lineHeight: "12px", letterSpacing: "0.06em" }],
      },
    },
  },
  plugins: [],
};
