const { withGradleProperties } = require("expo/config-plugins");

// By default, Expo's prebuild template ships every APK with native binaries
// for all four Android CPU architectures (armeabi-v7a, arm64-v8a, x86,
// x86_64) baked into one "fat" APK — the biggest single contributor to this
// app's build size, since every native module (Hermes, Reanimated, SVG...)
// ships once per architecture. Real phones only need arm64-v8a (every phone
// since ~2017) or, rarely, armeabi-v7a for very old 32-bit devices; x86/
// x86_64 only exist for Intel-based emulators.
//
// This can't just be edited in android/gradle.properties directly — that
// folder is gitignored and fully regenerated by `expo prebuild` (locally
// and on every EAS Build), so the change has to live in a config plugin
// that runs as part of that regeneration.
const ANDROID_ARCHITECTURES = "arm64-v8a";

function withAndroidAbiSplit(config) {
  return withGradleProperties(config, (config) => {
    config.modResults = config.modResults.filter(
      (item) => !(item.type === "property" && item.key === "reactNativeArchitectures")
    );
    config.modResults.push({
      type: "property",
      key: "reactNativeArchitectures",
      value: ANDROID_ARCHITECTURES,
    });
    return config;
  });
}

module.exports = withAndroidAbiSplit;
