const { withProjectBuildGradle } = require("expo/config-plugins");

// react-native-notify-kit pulls in modern AndroidX artifacts (Room 2.8.4,
// Guava 33.5, androidx.sqlite 2.6) that were themselves compiled against
// Kotlin 2.1. Gradle's "highest version wins" conflict resolution then drags
// kotlin-stdlib 2.1.20 onto the compile classpath, and the Kotlin 1.9.25
// compiler this project builds with can't read 2.1.0 class metadata —
// notify-kit's own Kotlin sources fail with "Class 'kotlin.Unit' was
// compiled with an incompatible version of Kotlin".
//
// The obvious fix — raising the project's Kotlin version — is a dead end on
// Expo SDK 52: expo-modules-core@2.2.3 only maps Compose compiler versions
// for Kotlin 1.9.24/1.9.25 (see its android/build.gradle `versionsMap`), so
// anything >= 2.0 breaks that module instead. Pinning the stdlib back down
// keeps both sides on metadata the 1.9.25 compiler understands; notify-kit's
// Kotlin layer is a thin bridge over its Java core, so it only needs stdlib
// APIs that long predate 2.x.
//
// Lives in a config plugin because android/ is gitignored and regenerated by
// every `expo prebuild` (locally and on EAS Build) — same reason as
// withAndroidAbiSplit.js.
const KOTLIN_STDLIB_VERSION = "1.9.25";

// Pinning the stdlib clears the bulk of the mismatch, but notify-kit's own
// AndroidX dependencies (Room 2.8.4, androidx.sqlite, work-runtime 2.11.1)
// still ship .kotlin_module metadata at version 2.1.0. Downgrading those is
// the riskier fix — notify-kit checks in a NotifeeCoreDatabase_Impl generated
// against Room 2.8.4 — so instead we tell the 1.9.25 compiler to read the
// newer metadata anyway. These are plain library APIs (DAOs, WorkManager
// entry points), not 2.x language features, so there's nothing in them the
// older compiler can't represent.
// The pin must NOT reach annotation-processor classpaths. Room's compiler is
// itself written against Kotlin 2.x and calls into classes that simply don't
// exist in 1.9.25 (it dies with NoClassDefFoundError kotlin/coroutines/jvm/
// internal/SpillingKt). Those processors run in their own classloader during
// javac, so they can keep the newer stdlib while the Kotlin *compile*
// classpath stays on 1.9.25.
const FORCE_BLOCK = `
// Added by ./plugins/withKotlinStdlibPin
allprojects {
  configurations.configureEach { cfg ->
    def cfgName = cfg.name.toLowerCase()
    if (!cfgName.contains("annotationprocessor") && !cfgName.contains("kapt") && !cfgName.contains("ksp")) {
      cfg.resolutionStrategy {
        force "org.jetbrains.kotlin:kotlin-stdlib:${KOTLIN_STDLIB_VERSION}"
        force "org.jetbrains.kotlin:kotlin-stdlib-jdk7:${KOTLIN_STDLIB_VERSION}"
        force "org.jetbrains.kotlin:kotlin-stdlib-jdk8:${KOTLIN_STDLIB_VERSION}"
        force "org.jetbrains.kotlin:kotlin-stdlib-common:${KOTLIN_STDLIB_VERSION}"
        force "org.jetbrains.kotlin:kotlin-reflect:${KOTLIN_STDLIB_VERSION}"
      }
    }
  }

  tasks.withType(org.jetbrains.kotlin.gradle.tasks.KotlinCompile).configureEach {
    kotlinOptions {
      freeCompilerArgs += ["-Xskip-metadata-version-check"]
    }
  }
}
`;

function withKotlinStdlibPin(config) {
  return withProjectBuildGradle(config, (config) => {
    if (config.modResults.language !== "groovy") {
      throw new Error("withKotlinStdlibPin only supports the Groovy build.gradle template");
    }
    if (!config.modResults.contents.includes("withKotlinStdlibPin")) {
      config.modResults.contents += FORCE_BLOCK;
    }
    return config;
  });
}

module.exports = withKotlinStdlibPin;
